### ISSUE TITLE
Just wanted to say You did amazing work on this tool! ( idk how to mark this as not an issue )

### ISSUE THREAD

**Issue by ghost** [m4k4v3l1/blindsqliscanner#1]
easy to run and understand !!! NO bulk code!!! making it easy to adjust program to whatever a person might  need ! 

Very little False positives!

Super clean detailed output separated to there own files !

Doesn't eat up CPU/Ram 

<3

**Comment by m4k4v3l1** [comment]
Anytime ! <3 
TY btw
all ready for a new discussions about such tools.

TG: @Terminal0x01

**Comment by Hail2Hydra** [comment]
Sorry Man Forgot to close it ! Hopefully it didn't cause you any trouble! !
It Runs literally 24/7 ! still amazing and now its my only go to tool the rest don't even come close to what you have created ! Id be lost without it !! Once Exams F@&K off we can do a collaborate on a project?? :) Mostly to do with injection and automating the sh!t Out of it ! Auto Dorking than Auto Dumping the important information oa separate files Per Vulnerability Found With DB information
